name: 'Zigbee Multi Switch and Child Mc'
packageKey: 'Zigbee_Multi_Switch-v5'
description: 'Devices: https://github.com/kyuchan-lee/Edge-Drivers-Beta/zigbee-multi-switch-v4.5-childs-edge/fingerprints.yml'
permissions:
  zigbee: {}
